version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/data/db
    networks:
      - db

networks:
  db: